#!/bin/bash
set -ex

docker build \
  --build-arg CMAKE_URL=http://192.168.150.108:8000/cmake-3.12.4-Linux-x86_64.tar.gz \
  --build-arg CLANG_URL=http://192.168.150.108:8000/clang+llvm-8.0.1-x86_64-linux-sles11.3.tar.xz \
  --build-arg HADOOP_URL=http://192.168.150.108:8000/hadoop-3.3.0.tar.gz \
  --build-arg DEP_URL=http://192.168.150.108:8000/dependency-clang-x86_64-Linux.tar.gz \
  -t oushu -f Dockerfile .
