#!/bin/bash
set -ex

#export RUN_UNITTEST=no
#export WITH_HORNET_EXECUTOR_ONLY=yes
export LIBHDFS3_CONF=

make install -C /home/oushu/oushu/hawq/src/backend

oushudb restart cluster -a
#oushudb restart main -a
