#!/bin/bash
set -ex

#export RUN_UNITTEST=no
#export WITH_HORNET_EXECUTOR_ONLY=yes
export LIBHDFS3_CONF=

oushudb stop cluster -a
cd /home/oushu/oushu/hawq/
make install -j8
#make install -C /home/oushu/oushu/hawq/src/backend

oushudb start cluster -a
#oushudb restart main -a
