#!/bin/bash
set -ex

export WITH_HORNET_EXECUTOR_ONLY=yes

WORKSPACE=/home/oushu/oushu/hornet/coverage
mkdir -p $WORKSPACE
cd $WORKSPACE

../bootstrap
make coverage -j8
lcov --base-directory . --directory . --capture --output-file CodeCoverage.info --ignore-errors graph;
lcov --remove CodeCoverage.info '/opt/*' '/usr/*' '/Library/*' '/Applications/*' '*/test/unit/*' '*/testutil/*' '*/protos/*' '*/proto/*' --output-file CodeCoverage.info.cleaned;
genhtml CodeCoverage.info.cleaned -o CodeCoverageReport;
